version: "3"
services:
  pihole:
# Container names have 2 appended because I didn't want to remove the existing containers - didn't want to blow up the DNS @home
    container_name: pihole2
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
#      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
      - "443:443/tcp"
#    network_mode: host
    networks:
      - pihole-unbound
    environment:
      TZ: 'America/Los_Angeles'
#      WEBPASSWORD: '*c!l2^Xx$3qG'
      FTLCONF_webserver_api_password: '*c!l2^Xx$3qG'
      DNSMASQ_LISTENING: local
      #PIHOLE_DNS_: '192.168.50.18#5053'
      FTLCONF_dns_upstreams: '192.168.50.22#5053'
# Volumes store your data between container upgrades
    volumes:
# Following lines need to be changed to reflect the actual local directories
      - '/home/dc3828102/docker/pihole/pihole:/etc/pihole'
      - '/home/dc3828102/docker/pihole/dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
      - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped
  unbound:
    container_name: unbound2
#    image: "mvance/unbound:latest"
    image: klutchell/unbound:latest
    ports:
      - "5053:53/tcp"
      - "5053:53/udp"
#    network_mode: host
    networks:
      - pihole-unbound
    volumes:
# This took me forever to figure out. klutchell/unbound image now uses a different directory to store the unbound.conf
# Store unbound.conf in the local directory as listed and the unbound container is going to use unbound.conf
      - '/home/dc3828102/docker_volumes/unbound:/etc/unbound/custom.conf.d'
    restart: unless-stopped

networks:
  pihole-unbound:
    driver: bridge
